In [ ]:
# Алексеев Д.П. (DSU-4, PYDA-21)
# Домашнее задание «Библиотека numpy. Вычислительные задачи» (#1)
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

# Задание 4
# В материалах занятия раздел “Задача 4 домашнего задания”

In [1]:
import numpy as np

In [2]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
user_input = int(input("Введите целое число N: "))
np_1 = np.arange(user_input-1, -1, -1)
np_1

Введите целое число N: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
np_2 = np.diag(np.arange(user_input-1, -1, -1))
print(np_2)

summ = 0
for i in range(user_input):
    summ += np.sum(np_2[i])

print("Сумма значений на главной диагонали:", summ)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений на главной диагонали: 45


In [4]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

# вводим коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )

# вводим коэффициенты при переменных в правой части уравнения
b = np.array( [ 4, 12, -3] )

In [5]:
# импортируем linalg
from numpy import linalg

# решение
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [6]:
# проверка решения
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [7]:
# Задание 4
# Имеется матрица покупок в интернет-магазине. 
# Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [8]:
# На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [9]:
# Найдите самого похожего пользователя. 
# Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
import matplotlib.pyplot as plt

In [23]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [29]:
for i in range(10):
    print("User_ID=", i+1, users_stats[i], next_user_stats, cosine(users_stats[i], next_user_stats))

User_ID= 1 [2 1 0 0 0 0] [0 1 2 0 0 0] 0.19999999999999996
User_ID= 2 [1 1 2 1 0 0] [0 1 2 0 0 0] 0.8451542547285165
User_ID= 3 [2 0 1 0 0 0] [0 1 2 0 0 0] 0.3999999999999999
User_ID= 4 [1 1 2 1 0 1] [0 1 2 0 0 0] 0.7905694150420948
User_ID= 5 [0 0 1 2 0 0] [0 1 2 0 0 0] 0.3999999999999999
User_ID= 6 [0 0 0 0 0 5] [0 1 2 0 0 0] 0.0
User_ID= 7 [1 0 0 0 0 0] [0 1 2 0 0 0] 0.0
User_ID= 8 [0 1 1 0 0 0] [0 1 2 0 0 0] 0.9486832980505138
User_ID= 9 [0 0 0 1 1 3] [0 1 2 0 0 0] 0.0
User_ID= 10 [1 0 0 2 1 4] [0 1 2 0 0 0] 0.0


In [31]:
# Ответ: самый похожий пользователь: User_ID = 8, косинусное сходство между векторами максимально и составляет 0.9486832980505138